using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ValuationBackend.Migrations
{
    /// <inheritdoc />
    public partial class ReorderReportIdColumnInLATables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Reorder columns in PastValuationsLA table
            migrationBuilder.Sql(@"
                -- Create temporary table with correct column order for PastValuationsLA
                CREATE TABLE ""PastValuationsLA_temp"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ReportId"" integer NOT NULL,
                    ""MasterFileId"" text NOT NULL,
                    ""MasterFileRefNo"" text NOT NULL,
                    ""FileNoGNDivision"" text,
                    ""Situation"" text,
                    ""DateOfValuation"" text,
                    ""PurposeOfValuation"" text,
                    ""PlanOfParticulars"" text,
                    ""Extent"" text,
                    ""Rate"" text,
                    ""Value"" text,
                    ""LocationLongitude"" text,
                    ""LocationLatitude"" text,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone,
                    CONSTRAINT ""PK_PastValuationsLA_temp"" PRIMARY KEY (""Id"")
                );
                
                -- Copy data with correct column order
                INSERT INTO ""PastValuationsLA_temp"" (""Id"", ""ReportId"", ""MasterFileId"", ""MasterFileRefNo"", ""FileNoGNDivision"", ""Situation"", ""DateOfValuation"", ""PurposeOfValuation"", ""PlanOfParticulars"", ""Extent"", ""Rate"", ""Value"", ""LocationLongitude"", ""LocationLatitude"", ""CreatedAt"", ""UpdatedAt"")
                SELECT ""Id"", ""ReportId"", ""MasterFileId"", ""MasterFileRefNo"", ""FileNoGNDivision"", ""Situation"", ""DateOfValuation"", ""PurposeOfValuation"", ""PlanOfParticulars"", ""Extent"", ""Rate"", ""Value"", ""LocationLongitude"", ""LocationLatitude"", ""CreatedAt"", ""UpdatedAt""
                FROM ""PastValuationsLA"";
                
                -- Drop original table
                DROP TABLE ""PastValuationsLA"";
                
                -- Rename temp table
                ALTER TABLE ""PastValuationsLA_temp"" RENAME TO ""PastValuationsLA"";
                
                -- Recreate indexes and constraints
                CREATE INDEX ""IX_PastValuationsLA_ReportId"" ON ""PastValuationsLA"" (""ReportId"");
                ALTER TABLE ""PastValuationsLA"" ADD CONSTRAINT ""FK_PastValuationsLA_Reports_ReportId"" 
                    FOREIGN KEY (""ReportId"") REFERENCES ""Reports"" (""ReportId"") ON DELETE CASCADE;
            ");
            
            // Reorder columns in SalesEvidencesLA table  
            migrationBuilder.Sql(@"
                -- Create temporary table with correct column order for SalesEvidencesLA
                CREATE TABLE ""SalesEvidencesLA_temp"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ReportId"" integer NOT NULL,
                    ""MasterFileId"" text NOT NULL,
                    ""AssetNumber"" text,
                    ""MasterFileRefNo"" text NOT NULL,
                    ""Road"" text,
                    ""Village"" text,
                    ""Owner"" text,
                    ""Occupier"" text,
                    ""Vendor"" text,
                    ""DeedNumber"" text,
                    ""Description"" text,
                    ""FloorRate"" text,
                    ""DeedAttestedNumber"" text,
                    ""NotaryName"" text,
                    ""LotNumber"" text,
                    ""PlanNumber"" text,
                    ""PlanDate"" text,
                    ""Extent"" text,
                    ""Consideration"" text,
                    ""Remarks"" text,
                    ""Rate"" text,
                    ""RateType"" text,
                    ""LocationLongitude"" text,
                    ""LocationLatitude"" text,
                    ""LandRegistryReferences"" text,
                    ""Situation"" text,
                    ""DescriptionOfProperty"" text,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone,
                    CONSTRAINT ""PK_SalesEvidencesLA_temp"" PRIMARY KEY (""Id"")
                );
                
                -- Copy data with correct column order
                INSERT INTO ""SalesEvidencesLA_temp"" (""Id"", ""ReportId"", ""MasterFileId"", ""AssetNumber"", ""MasterFileRefNo"", ""Road"", ""Village"", ""Owner"", ""Occupier"", ""Vendor"", ""DeedNumber"", ""Description"", ""FloorRate"", ""DeedAttestedNumber"", ""NotaryName"", ""LotNumber"", ""PlanNumber"", ""PlanDate"", ""Extent"", ""Consideration"", ""Remarks"", ""Rate"", ""RateType"", ""LocationLongitude"", ""LocationLatitude"", ""LandRegistryReferences"", ""Situation"", ""DescriptionOfProperty"", ""CreatedAt"", ""UpdatedAt"")
                SELECT ""Id"", ""ReportId"", ""MasterFileId"", ""AssetNumber"", ""MasterFileRefNo"", ""Road"", ""Village"", ""Owner"", ""Occupier"", ""Vendor"", ""DeedNumber"", ""Description"", ""FloorRate"", ""DeedAttestedNumber"", ""NotaryName"", ""LotNumber"", ""PlanNumber"", ""PlanDate"", ""Extent"", ""Consideration"", ""Remarks"", ""Rate"", ""RateType"", ""LocationLongitude"", ""LocationLatitude"", ""LandRegistryReferences"", ""Situation"", ""DescriptionOfProperty"", ""CreatedAt"", ""UpdatedAt""
                FROM ""SalesEvidencesLA"";
                
                -- Drop original table
                DROP TABLE ""SalesEvidencesLA"";
                
                -- Rename temp table
                ALTER TABLE ""SalesEvidencesLA_temp"" RENAME TO ""SalesEvidencesLA"";
                
                -- Recreate indexes and constraints
                CREATE INDEX ""IX_SalesEvidencesLA_ReportId"" ON ""SalesEvidencesLA"" (""ReportId"");
                ALTER TABLE ""SalesEvidencesLA"" ADD CONSTRAINT ""FK_SalesEvidencesLA_Reports_ReportId"" 
                    FOREIGN KEY (""ReportId"") REFERENCES ""Reports"" (""ReportId"") ON DELETE CASCADE;
            ");
            
            // Reorder columns in RentalEvidencesLA table
            migrationBuilder.Sql(@"
                -- Create temporary table with correct column order for RentalEvidencesLA
                CREATE TABLE ""RentalEvidencesLA_temp"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ReportId"" integer NOT NULL,
                    ""MasterFileId"" text NOT NULL,
                    ""AssessmentNo"" text,
                    ""MasterFileRefNo"" text NOT NULL,
                    ""Owner"" text,
                    ""Occupier"" text,
                    ""Description"" text,
                    ""FloorRateSQFT"" text,
                    ""RatePerSqft"" text,
                    ""RatePerMonth"" text,
                    ""LocationLongitude"" text,
                    ""LocationLatitude"" text,
                    ""HeadOfTerms"" text,
                    ""Situation"" text,
                    ""Remarks"" text,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone,
                    CONSTRAINT ""PK_RentalEvidencesLA_temp"" PRIMARY KEY (""Id"")
                );
                
                -- Copy data with correct column order
                INSERT INTO ""RentalEvidencesLA_temp"" (""Id"", ""ReportId"", ""MasterFileId"", ""AssessmentNo"", ""MasterFileRefNo"", ""Owner"", ""Occupier"", ""Description"", ""FloorRateSQFT"", ""RatePerSqft"", ""RatePerMonth"", ""LocationLongitude"", ""LocationLatitude"", ""HeadOfTerms"", ""Situation"", ""Remarks"", ""CreatedAt"", ""UpdatedAt"")
                SELECT ""Id"", ""ReportId"", ""MasterFileId"", ""AssessmentNo"", ""MasterFileRefNo"", ""Owner"", ""Occupier"", ""Description"", ""FloorRateSQFT"", ""RatePerSqft"", ""RatePerMonth"", ""LocationLongitude"", ""LocationLatitude"", ""HeadOfTerms"", ""Situation"", ""Remarks"", ""CreatedAt"", ""UpdatedAt""
                FROM ""RentalEvidencesLA"";
                
                -- Drop original table
                DROP TABLE ""RentalEvidencesLA"";
                
                -- Rename temp table
                ALTER TABLE ""RentalEvidencesLA_temp"" RENAME TO ""RentalEvidencesLA"";
                
                -- Recreate indexes and constraints
                CREATE INDEX ""IX_RentalEvidencesLA_ReportId"" ON ""RentalEvidencesLA"" (""ReportId"");
                ALTER TABLE ""RentalEvidencesLA"" ADD CONSTRAINT ""FK_RentalEvidencesLA_Reports_ReportId"" 
                    FOREIGN KEY (""ReportId"") REFERENCES ""Reports"" (""ReportId"") ON DELETE CASCADE;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Note: Rolling back column reordering would be complex and data-destructive
            // This migration is designed to be forward-only for column organization
            // If rollback is absolutely necessary, it would require recreating tables
            // with the original column order, but this is not recommended in production
            throw new NotSupportedException("Rolling back column reordering is not supported. This migration is designed to be forward-only.");
        }
    }
}
