using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ValuationBackend.Migrations
{
    /// <inheritdoc />
    public partial class ReorderReportIdColumnInBuildingRatesLA : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Reorder columns in BuildingRatesLA table to have ReportId right after Id
            migrationBuilder.Sql(@"
                -- Create temporary table with correct column order for BuildingRatesLA
                CREATE TABLE ""BuildingRatesLA_temp"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ReportId"" integer NOT NULL,
                    ""MasterFileId"" text NOT NULL,
                    ""AssessmentNumber"" text,
                    ""Owner"" text,
                    ""ConstructedBy"" text,
                    ""YearOfConstruction"" text,
                    ""DescriptionOfProperty"" text,
                    ""FloorAreaSQFT"" text,
                    ""RatePerSQFT"" text,
                    ""Cost"" text,
                    ""Remarks"" text,
                    ""LocationLatitude"" text,
                    ""LocationLongitude"" text,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone,
                    CONSTRAINT ""PK_BuildingRatesLA_temp"" PRIMARY KEY (""Id"")
                );
                
                -- Copy data with correct column order
                INSERT INTO ""BuildingRatesLA_temp"" (""Id"", ""ReportId"", ""MasterFileId"", ""AssessmentNumber"", ""Owner"", ""ConstructedBy"", ""YearOfConstruction"", ""DescriptionOfProperty"", ""FloorAreaSQFT"", ""RatePerSQFT"", ""Cost"", ""Remarks"", ""LocationLatitude"", ""LocationLongitude"", ""CreatedAt"", ""UpdatedAt"")
                SELECT ""Id"", ""ReportId"", ""MasterFileId"", ""AssessmentNumber"", ""Owner"", ""ConstructedBy"", ""YearOfConstruction"", ""DescriptionOfProperty"", ""FloorAreaSQFT"", ""RatePerSQFT"", ""Cost"", ""Remarks"", ""LocationLatitude"", ""LocationLongitude"", ""CreatedAt"", ""UpdatedAt""
                FROM ""BuildingRatesLA"";
                
                -- Drop original table
                DROP TABLE ""BuildingRatesLA"";
                
                -- Rename temp table
                ALTER TABLE ""BuildingRatesLA_temp"" RENAME TO ""BuildingRatesLA"";
                
                -- Recreate indexes and constraints
                CREATE INDEX ""IX_BuildingRatesLA_ReportId"" ON ""BuildingRatesLA"" (""ReportId"");
                ALTER TABLE ""BuildingRatesLA"" ADD CONSTRAINT ""FK_BuildingRatesLA_Reports_ReportId"" 
                    FOREIGN KEY (""ReportId"") REFERENCES ""Reports"" (""ReportId"") ON DELETE CASCADE;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Note: Rolling back column reordering would be complex and data-destructive
            // This migration is designed to be forward-only for column organization
            // If rollback is absolutely necessary, it would require recreating tables
            // with the original column order, but this is not recommended in production
            throw new NotSupportedException("Rolling back column reordering is not supported. This migration is designed to be forward-only.");
        }
    }
}
