// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ValuationBackend.Data;

#nullable disable

namespace ValuationBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ValuationBackend.Models.ConditionReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccessCategoryDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AcquiredExtent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AcquiringOfficerSignature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AcquisitionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssessmentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AtLotNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AtPlanNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BoundaryBottom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BoundaryEast")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BoundaryNorth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BoundarySouth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BoundaryWest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuildingDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuildingInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChiefValuerRepresentativeSignature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DateOfSection3BA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DatePrepared")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepthOfLand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionOfLand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailsOfBusiness")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Frontage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GramasewakaSignature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LandUseDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LandUseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LevelWithAccess")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MasterFileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameOfTheLand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameOfTheVillage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherConstructionsDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherConstructionsInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlantationDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PpCadLotNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PpCadNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoadName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConditionReports");
                });

            modelBuilder.Entity("ValuationBackend.Models.LandMiscellaneousMasterFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MasterFileNo")
                        .HasColumnType("integer");

                    b.Property<string>("PlanNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestingAuthorityReferenceNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LandMiscellaneousMasterFiles");
                });

            modelBuilder.Entity("ValuationBackend.Models.RatingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LocalAuthority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RatingReferenceNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearOfRevision")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RatingRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
